service: serverless-python-langchain
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true

package:
  patterns:
    - '!.venv/**'

functions:
  hello:
    handler: handler.hello
    environment:
      OPENAI_API_KEY: ${ssm:OPENAI_API_KEY}
    layers:
      - Ref: PythonRequirementsLambdaLayer
